name: Flutter Web
on:
   - push
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - name: "Upload build web"
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
      - name: 🚀 Deploy app on gh-pages branch
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: ./build/web  # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAN: true  # Automatically remove deleted files from the deploy branch.
